### ISSUE TITLE
Incorrect steps on https://github.com/greyhoundforty/IBMCloud-Terraform-Examples/tree/master/VPC-SingleZone

### ISSUE THREAD

**Issue by doyoungim999** [greyhoundforty/IBMCloud-Terraform-Examples#13]
on https://github.com/greyhoundforty/IBMCloud-Terraform-Examples/tree/master/VPC-SingleZone 

the following step does not working as written. Please correct. 

Step 1: Clone repo

$ git clone https://github.com/greyhoundforty/IBMCloud-Terraform-Examples.git
$ cd VPC-Gen2

**Comment by greyhoundforty** [comment]
This should be correct now. I need to go back through and update for more recent terraform versions
